### ISSUE TITLE
Allow using same attribute multiple times

### ISSUE THREAD

**Issue by dbarr99** [sdmx-twg/sdmx-ml-v2_1#19] opened 2016-01-27 09:37 UTC
Exchange data with multiple "flags" or "control codes" at the same level (e.g. observation), e.g. using OBS_STATUS is difficult in SDMX and has a stop-gap SDMX guidelines recommendation.  Have a practical way to attach the same attribute multiple times in a data message.

**Comment by Tzaphkiel** [comment] 2018-06-15 14:10
Duplicate of #22

**Closed by Tzaphkiel** 2018-06-15 14:10 UTC
